---
title: Vijay Masharani
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: vmasharani@mica.edu
description: Designer+ . Bay area now / brooklyn soon.
baseurl:
url:
markdown: kramdown
theme: minima
assets:
  sources: dsn3/sass/minima/fonts.scss
plugins:
- jekyll-feed
