---
title: Vijay Masharani
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: vmasharani@mica.edu
description: 
  Designer+ . Bay area now / brooklyn soon.


baseurl:
url:
# twitter_username: jekyllrb
# github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
