---
title: Vijay Masharani
timezone: PST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: vmasharani@mica.edu
description: 'Vijay Masharani / Designer+

'
baseurl:
url:
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
